import { Types } from "mongoose";
import { describe, expect, it } from "vitest";

import { createObjectId } from "@/utils/clientHelpers";
import { Note, Project, User } from "@/utils/mongoose";
import { removeDoneProjectNotes, upsertNote } from "@/utils/note/noteIntake";
import { attachOrUpdateShare } from "@/utils/share/shareIntake";

import { useTestDb } from "../db/testDb";

useTestDb();

const seed = async (share?: { canEdit: boolean }) => {
  const owner = await User.create({ email: "owner@example.com", username: "owner" });
  const visitor = await User.create({ email: "visitor@example.com", username: "visitor" });
  const project = await Project.create({ title: "Rough cut", user: owner._id });
  if (share) await attachOrUpdateShare(project, { url: "rough-cut", ...share });
  return {
    ownerId: owner._id.toString(),
    visitorId: visitor._id.toString(),
    projectId: project._id.toString(),
  };
};

const noteInput = (projectId: string, overrides: Record<string, unknown> = {}) => ({
  _id: new Types.ObjectId().toString(),
  content: "Trim the intro",
  time: 12,
  done: false,
  project: projectId,
  ...overrides,
});

const seedNote = async (projectId: string, fields: Record<string, unknown> = {}) => {
  const note = await Note.create({ content: "Original", project: projectId, ...fields });
  await Project.updateOne({ _id: projectId }, { $push: { notes: note._id } });
  return note;
};

const guest = () => null;
const visitor = (ids: { visitorId: string }) => ids.visitorId;

describe("upsertNote on create", () => {
  it("lets the owner create a Note, linking it to the Project with its author", async () => {
    const { ownerId, projectId } = await seed();
    const input = noteInput(projectId);

    const result = await upsertNote(input, ownerId);

    if (result.kind !== "ok") throw new Error(`expected ok, got ${result.kind}`);
    expect(result.note).toMatchObject({
      content: "Trim the intro",
      user: { _id: ownerId, username: "owner", role: "owner" },
    });
    expect(JSON.stringify(result.note)).not.toContain("owner@example.com");
    expect((await Project.findById(projectId)).notes.map(String)).toEqual([input._id]);
  });

  it("accepts a Note id generated by the client", async () => {
    const { ownerId, projectId } = await seed();
    const input = noteInput(projectId, { _id: createObjectId() });

    const result = await upsertNote(input, ownerId);

    expect(result.kind).toBe("ok");
    expect((await Note.findById(input._id))?.content).toBe("Trim the intro");
  });

  it.each([
    ["a guest", guest],
    ["another user", visitor],
  ])("forbids %s without a Share", async (_label, caller) => {
    const ids = await seed();

    expect(await upsertNote(noteInput(ids.projectId), caller(ids))).toEqual({ kind: "forbidden" });
    expect(await Note.countDocuments()).toBe(0);
    expect((await Project.findById(ids.projectId)).notes).toHaveLength(0);
  });

  it.each([
    ["a guest", guest],
    ["another user", visitor],
  ])("forbids %s when the Share has canEdit false", async (_label, caller) => {
    const ids = await seed({ canEdit: false });

    expect(await upsertNote(noteInput(ids.projectId), caller(ids))).toEqual({ kind: "forbidden" });
    expect(await Note.countDocuments()).toBe(0);
  });

  it("lets a guest create through an editable Share, without an author", async () => {
    const { ownerId, projectId } = await seed({ canEdit: true });

    const result = await upsertNote(noteInput(projectId, { user: ownerId }), null);

    expect(result.kind).toBe("ok");
    const stored = await Note.findOne();
    expect(stored.user).toBeUndefined();
    expect((await Project.findById(projectId)).notes).toHaveLength(1);
  });

  it("lets another user create through an editable Share as themselves", async () => {
    const { ownerId, visitorId, projectId } = await seed({ canEdit: true });

    const result = await upsertNote(noteInput(projectId, { user: ownerId }), visitorId);

    expect((await Note.findOne()).user.toString()).toBe(visitorId);
    if (result.kind !== "ok") throw new Error(`expected ok, got ${result.kind}`);
    expect(result.note.user).toEqual({ _id: visitorId, username: "visitor", role: "member" });
  });

  it("returns notFound for a missing Project and saves nothing", async () => {
    const { ownerId } = await seed();

    expect(await upsertNote(noteInput(new Types.ObjectId().toString()), ownerId)).toEqual({
      kind: "notFound",
    });
    expect(await Note.countDocuments()).toBe(0);
  });

  it.each([["not-an-id"], [{ $ne: null }], [{ _bsontype: "ObjectId", $ne: null }], [undefined]])(
    "returns invalid for the malformed Project id %j and saves nothing",
    async (project) => {
      const { ownerId, projectId } = await seed();

      expect(await upsertNote(noteInput(projectId, { project }), ownerId)).toEqual({
        kind: "invalid",
      });
      expect(await Note.countDocuments()).toBe(0);
    },
  );

  it.each([["not-an-id"], [{ $ne: null }], [{ _bsontype: "ObjectId", $ne: null }], [42], [null]])(
    "returns invalid for the malformed Note id %j and saves nothing",
    async (_id) => {
      const { ownerId, projectId } = await seed();
      await seedNote(projectId, { user: ownerId });

      expect(await upsertNote(noteInput(projectId, { _id }), ownerId)).toEqual({
        kind: "invalid",
      });
      expect((await Note.find()).map((note) => note.content)).toEqual(["Original"]);
    },
  );
});

describe("upsertNote field validation", () => {
  it.each([
    ["no content", { content: undefined }],
    ["empty content", { content: "" }],
    ["non-string content", { content: { $gt: "" } }],
    ["a non-number time", { time: "soon" }],
    ["a non-finite time", { time: Number.NaN }],
    ["a non-boolean done", { done: "yes" }],
  ])("returns invalid on create with %s and saves nothing", async (_label, overrides) => {
    const { ownerId, projectId } = await seed();

    expect(await upsertNote(noteInput(projectId, overrides), ownerId)).toEqual({
      kind: "invalid",
    });
    expect(await Note.countDocuments()).toBe(0);
  });

  it.each([
    ["empty content", { content: "" }],
    ["a non-number time", { time: "soon" }],
    ["a non-boolean done", { done: 0 }],
  ])("returns invalid on update with %s and leaves the Note unchanged", async (_label, fields) => {
    const { ownerId, projectId } = await seed();
    const note = await seedNote(projectId, { user: ownerId, time: 3 });

    const result = await upsertNote(
      { _id: note._id.toString(), project: projectId, ...fields } as never,
      ownerId,
    );

    expect(result).toEqual({ kind: "invalid" });
    expect(await Note.findById(note._id)).toMatchObject({ content: "Original", time: 3 });
  });

  it.each([
    ["no time", { time: undefined }],
    ["a null time", { time: null }],
  ])("creates with time 0 given %s", async (_label, overrides) => {
    const { ownerId, projectId } = await seed();
    const input = noteInput(projectId, overrides);

    const result = await upsertNote(input as never, ownerId);

    expect(result.kind).toBe("ok");
    expect(await Note.findById(input._id)).toMatchObject({ content: "Trim the intro", time: 0 });
  });

  it("leaves the time unchanged on an update with a null time", async () => {
    const { ownerId, projectId } = await seed();
    const note = await seedNote(projectId, { user: ownerId, time: 3 });

    const result = await upsertNote(
      { _id: note._id.toString(), project: projectId, content: "Edited", time: null } as never,
      ownerId,
    );

    expect(result.kind).toBe("ok");
    expect(await Note.findById(note._id)).toMatchObject({ content: "Edited", time: 3 });
  });

  it("creates with done false given a null done", async () => {
    const { ownerId, projectId } = await seed();
    const input = noteInput(projectId, { done: null });

    const result = await upsertNote(input as never, ownerId);

    expect(result.kind).toBe("ok");
    expect(await Note.findById(input._id)).toMatchObject({ done: false });
  });

  it.each([
    ["echoes the null done", { done: null }],
    ["omits done", {}],
  ])("edits a legacy Note stored with a null done when the update %s", async (_l, fields) => {
    const { ownerId, projectId } = await seed();
    const note = await seedNote(projectId, { user: ownerId });
    await Note.collection.updateOne({ _id: note._id }, { $set: { done: null } });

    const result = await upsertNote(
      { _id: note._id.toString(), project: projectId, content: "Edited", ...fields } as never,
      ownerId,
    );

    expect(result.kind).toBe("ok");
    expect((await Note.collection.findOne({ _id: note._id })) as object).toMatchObject({
      content: "Edited",
      done: null,
    });
  });

  it("lets an update omit content", async () => {
    const { ownerId, projectId } = await seed();
    const note = await seedNote(projectId, { user: ownerId });

    const result = await upsertNote(
      { _id: note._id.toString(), project: projectId, done: true } as never,
      ownerId,
    );

    expect(result.kind).toBe("ok");
    expect(await Note.findById(note._id)).toMatchObject({ content: "Original", done: true });
  });
});

describe("upsertNote on update", () => {
  it("lets the owner update content, time and done", async () => {
    const { ownerId, projectId } = await seed();
    const note = await seedNote(projectId, { user: ownerId });

    const result = await upsertNote(
      noteInput(projectId, { _id: note._id.toString(), content: "Edited", time: 40, done: true }),
      ownerId,
    );

    expect(result.kind).toBe("ok");
    expect(await Note.findById(note._id)).toMatchObject({
      content: "Edited",
      time: 40,
      done: true,
    });
  });

  it("leaves fields the payload omits untouched", async () => {
    const { ownerId, projectId } = await seed();
    const note = await seedNote(projectId, { time: 40, done: true });

    await upsertNote({ _id: note._id.toString(), content: "Edited", project: projectId }, ownerId);

    expect(await Note.findById(note._id)).toMatchObject({
      content: "Edited",
      time: 40,
      done: true,
    });
  });

  it("decides permission from the stored Note's Project, not the payload", async () => {
    const { ownerId, projectId: privateProjectId } = await seed();
    const editable = await Project.create({ title: "Open", user: ownerId });
    await attachOrUpdateShare(editable, { url: "open", canEdit: true });
    const note = await seedNote(privateProjectId);

    const result = await upsertNote(
      noteInput(editable._id.toString(), { _id: note._id.toString(), content: "Changed" }),
      null,
    );

    expect(result).toEqual({ kind: "forbidden" });
    expect((await Note.findById(note._id)).content).toBe("Original");
  });

  it("keeps project and user when the payload tries to change them", async () => {
    const { ownerId, visitorId, projectId } = await seed({ canEdit: true });
    const other = await Project.create({ title: "Other", user: visitorId });
    const note = await seedNote(projectId, { user: ownerId });

    const result = await upsertNote(
      noteInput(other._id.toString(), {
        _id: note._id.toString(),
        content: "Edited",
        user: visitorId,
      }),
      visitorId,
    );

    expect(result.kind).toBe("ok");
    const stored = await Note.findById(note._id);
    expect(stored.content).toBe("Edited");
    expect(stored.project.toString()).toBe(projectId);
    expect(stored.user.toString()).toBe(ownerId);
    expect((await Project.findById(other._id)).notes).toHaveLength(0);
  });

  it("returns notFound when the stored Note's Project is gone", async () => {
    const { ownerId, projectId } = await seed();
    const note = await seedNote(projectId);
    await Project.deleteOne({ _id: projectId });

    const result = await upsertNote(noteInput(projectId, { _id: note._id.toString() }), ownerId);

    expect(result).toEqual({ kind: "notFound" });
  });
});

describe("removeDoneProjectNotes", () => {
  it("lets the owner remove done Notes, pulling them from the Project", async () => {
    const { ownerId, projectId } = await seed();
    const done = await seedNote(projectId, { done: true });
    const open = await seedNote(projectId);

    const result = await removeDoneProjectNotes(projectId, ownerId);

    if (result.kind !== "ok") throw new Error(`expected ok, got ${result.kind}`);
    expect(result.notes.map((note) => note._id.toString())).toEqual([open._id.toString()]);
    expect(await Note.findById(done._id)).toBeNull();
    expect((await Project.findById(projectId)).notes.map(String)).toEqual([open._id.toString()]);
  });

  it("returns the survivors with their authors as the public view", async () => {
    const { ownerId, visitorId, projectId } = await seed();
    await User.updateOne({ _id: visitorId }, { username: "visitor@example.com" });
    await seedNote(projectId, { user: ownerId });
    await seedNote(projectId, { user: visitorId });
    await seedNote(projectId);

    const result = await removeDoneProjectNotes(projectId, ownerId);

    if (result.kind !== "ok") throw new Error(`expected ok, got ${result.kind}`);
    expect(result.notes.map((note) => note.user)).toEqual([
      { _id: ownerId, username: "owner", role: "owner" },
      { _id: visitorId, role: "member" },
      undefined,
    ]);
    expect(JSON.stringify(result.notes)).not.toMatch(/@example\.com/);
  });

  it("lets a guest remove done Notes through an editable Share", async () => {
    const { projectId } = await seed({ canEdit: true });
    await seedNote(projectId, { done: true });
    const open = await seedNote(projectId);

    const result = await removeDoneProjectNotes(projectId, null);

    if (result.kind !== "ok") throw new Error(`expected ok, got ${result.kind}`);
    expect(result.notes.map((note) => note._id.toString())).toEqual([open._id.toString()]);
    expect(await Note.countDocuments()).toBe(1);
  });

  it.each([
    ["a guest", guest],
    ["another user", visitor],
  ])("forbids %s when the Share has canEdit false", async (_label, caller) => {
    const ids = await seed({ canEdit: false });
    await seedNote(ids.projectId, { done: true });

    expect(await removeDoneProjectNotes(ids.projectId, caller(ids))).toEqual({
      kind: "forbidden",
    });
    expect(await Note.countDocuments()).toBe(1);
  });

  it("returns notFound for a missing Project", async () => {
    const { ownerId } = await seed();

    expect(await removeDoneProjectNotes(new Types.ObjectId().toString(), ownerId)).toEqual({
      kind: "notFound",
    });
  });

  it.each([["not-an-id"], [{ $ne: null }], [{ _bsontype: "ObjectId", $ne: null }], [undefined]])(
    "returns invalid for the malformed project id %j",
    async (projectId) => {
      const { ownerId } = await seed();

      expect(await removeDoneProjectNotes(projectId, ownerId)).toEqual({ kind: "invalid" });
    },
  );
});
