import { Types } from "mongoose";
import { describe, expect, it } from "vitest";

import { createObjectId } from "@/utils/clientHelpers";
import { Note, Project, User } from "@/utils/mongoose";
import { removeDoneProjectNotes, upsertNote } from "@/utils/note/noteIntake";
import { attachOrUpdateShare } from "@/utils/share/shareIntake";

import { useTestDb } from "../db/testDb";

useTestDb();

const seed = async (share?: { canEdit: boolean }) => {
  const owner = await User.create({ email: "owner@example.com", username: "owner" });
  const visitor = await User.create({ email: "visitor@example.com", username: "visitor" });
  const project = await Project.create({ title: "Rough cut", user: owner._id });
  if (share) await attachOrUpdateShare(project, { url: "rough-cut", ...share });
  return {
    ownerId: owner._id.toString(),
    visitorId: visitor._id.toString(),
    projectId: project._id.toString(),
  };
};

const noteInput = (projectId: string, overrides: Record<string, unknown> = {}) => ({
  _id: new Types.ObjectId().toString(),
  content: "Trim the intro",
  time: 12,
  done: false,
  project: projectId,
  ...overrides,
});

const seedNote = async (projectId: string, fields: Record<string, unknown> = {}) => {
  const note = await Note.create({ content: "Original", project: projectId, ...fields });
  await Project.updateOne({ _id: projectId }, { $push: { notes: note._id } });
  return note;
};

const guest = () => null;
const visitor = (ids: { visitorId: string }) => ids.visitorId;

describe("upsertNote on create", () => {
  it("lets the owner create a Note, linking it to the Project with its author", async () => {
    const { ownerId, projectId } = await seed();
    const input = noteInput(projectId);

    const result = await upsertNote(input, ownerId);

    if (result.kind !== "ok") throw new Error(`expected ok, got ${result.kind}`);
    expect(result.note).toMatchObject({
      content: "Trim the intro",
      user: { _id: ownerId, username: "owner" },
    });
    expect(JSON.stringify(result.note)).not.toContain("owner@example.com");
    expect((await Project.findById(projectId)).notes.map(String)).toEqual([input._id]);
  });

  it("accepts a Note id generated by the client", async () => {
    const { ownerId, projectId } = await seed();
    const input = noteInput(projectId, { _id: createObjectId() });

    const result = await upsertNote(input, ownerId);

    expect(result.kind).toBe("ok");
    expect((await Note.findById(input._id))?.content).toBe("Trim the intro");
  });

  it.each([
    ["a guest", guest],
    ["another user", visitor],
  ])("forbids %s without a Share", async (_label, caller) => {
    const ids = await seed();

    expect(await upsertNote(noteInput(ids.projectId), caller(ids))).toEqual({ kind: "forbidden" });
    expect(await Note.countDocuments()).toBe(0);
    expect((await Project.findById(ids.projectId)).notes).toHaveLength(0);
  });

  it.each([
    ["a guest", guest],
    ["another user", visitor],
  ])("forbids %s when the Share has canEdit false", async (_label, caller) => {
    const ids = await seed({ canEdit: false });

    expect(await upsertNote(noteInput(ids.projectId), caller(ids))).toEqual({ kind: "forbidden" });
    expect(await Note.countDocuments()).toBe(0);
  });

  it("lets a guest create through an editable Share, without an author", async () => {
    const { ownerId, projectId } = await seed({ canEdit: true });

    const result = await upsertNote(noteInput(projectId, { user: ownerId }), null);

    expect(result.kind).toBe("ok");
    const stored = await Note.findOne();
    expect(stored.user).toBeUndefined();
    expect((await Project.findById(projectId)).notes).toHaveLength(1);
  });

  it("lets another user create through an editable Share as themselves", async () => {
    const { ownerId, visitorId, projectId } = await seed({ canEdit: true });

    await upsertNote(noteInput(projectId, { user: ownerId }), visitorId);

    expect((await Note.findOne()).user.toString()).toBe(visitorId);
  });

  it("returns notFound for a missing or malformed Project and saves nothing", async () => {
    const { ownerId } = await seed();

    expect(await upsertNote(noteInput(new Types.ObjectId().toString()), ownerId)).toEqual({
      kind: "notFound",
    });
    expect(await upsertNote(noteInput("not-an-id"), ownerId)).toEqual({ kind: "notFound" });
    expect(await Note.countDocuments()).toBe(0);
  });
});

describe("upsertNote on update", () => {
  it("lets the owner update content, time and done", async () => {
    const { ownerId, projectId } = await seed();
    const note = await seedNote(projectId, { user: ownerId });

    const result = await upsertNote(
      noteInput(projectId, { _id: note._id.toString(), content: "Edited", time: 40, done: true }),
      ownerId,
    );

    expect(result.kind).toBe("ok");
    expect(await Note.findById(note._id)).toMatchObject({
      content: "Edited",
      time: 40,
      done: true,
    });
  });

  it("leaves fields the payload omits untouched", async () => {
    const { ownerId, projectId } = await seed();
    const note = await seedNote(projectId, { time: 40, done: true });

    await upsertNote({ _id: note._id.toString(), content: "Edited", project: projectId }, ownerId);

    expect(await Note.findById(note._id)).toMatchObject({
      content: "Edited",
      time: 40,
      done: true,
    });
  });

  it("decides permission from the stored Note's Project, not the payload", async () => {
    const { ownerId, projectId: privateProjectId } = await seed();
    const editable = await Project.create({ title: "Open", user: ownerId });
    await attachOrUpdateShare(editable, { url: "open", canEdit: true });
    const note = await seedNote(privateProjectId);

    const result = await upsertNote(
      noteInput(editable._id.toString(), { _id: note._id.toString(), content: "Changed" }),
      null,
    );

    expect(result).toEqual({ kind: "forbidden" });
    expect((await Note.findById(note._id)).content).toBe("Original");
  });

  it("keeps project and user when the payload tries to change them", async () => {
    const { ownerId, visitorId, projectId } = await seed({ canEdit: true });
    const other = await Project.create({ title: "Other", user: visitorId });
    const note = await seedNote(projectId, { user: ownerId });

    const result = await upsertNote(
      noteInput(other._id.toString(), {
        _id: note._id.toString(),
        content: "Edited",
        user: visitorId,
      }),
      visitorId,
    );

    expect(result.kind).toBe("ok");
    const stored = await Note.findById(note._id);
    expect(stored.content).toBe("Edited");
    expect(stored.project.toString()).toBe(projectId);
    expect(stored.user.toString()).toBe(ownerId);
    expect((await Project.findById(other._id)).notes).toHaveLength(0);
  });

  it("returns notFound when the stored Note's Project is gone", async () => {
    const { ownerId, projectId } = await seed();
    const note = await seedNote(projectId);
    await Project.deleteOne({ _id: projectId });

    const result = await upsertNote(noteInput(projectId, { _id: note._id.toString() }), ownerId);

    expect(result).toEqual({ kind: "notFound" });
  });
});

describe("removeDoneProjectNotes", () => {
  it("lets the owner remove done Notes, pulling them from the Project", async () => {
    const { ownerId, projectId } = await seed();
    const done = await seedNote(projectId, { done: true });
    const open = await seedNote(projectId);

    const result = await removeDoneProjectNotes(projectId, ownerId);

    if (result.kind !== "ok") throw new Error(`expected ok, got ${result.kind}`);
    expect(result.notes.map((note) => note._id.toString())).toEqual([open._id.toString()]);
    expect(await Note.findById(done._id)).toBeNull();
    expect((await Project.findById(projectId)).notes.map(String)).toEqual([open._id.toString()]);
  });

  it("lets a guest remove done Notes through an editable Share", async () => {
    const { projectId } = await seed({ canEdit: true });
    await seedNote(projectId, { done: true });
    const open = await seedNote(projectId);

    const result = await removeDoneProjectNotes(projectId, null);

    if (result.kind !== "ok") throw new Error(`expected ok, got ${result.kind}`);
    expect(result.notes.map((note) => note._id.toString())).toEqual([open._id.toString()]);
    expect(await Note.countDocuments()).toBe(1);
  });

  it.each([
    ["a guest", guest],
    ["another user", visitor],
  ])("forbids %s when the Share has canEdit false", async (_label, caller) => {
    const ids = await seed({ canEdit: false });
    await seedNote(ids.projectId, { done: true });

    expect(await removeDoneProjectNotes(ids.projectId, caller(ids))).toEqual({
      kind: "forbidden",
    });
    expect(await Note.countDocuments()).toBe(1);
  });

  it("returns notFound for a missing or malformed project id", async () => {
    const { ownerId } = await seed();

    expect(await removeDoneProjectNotes(new Types.ObjectId().toString(), ownerId)).toEqual({
      kind: "notFound",
    });
    expect(await removeDoneProjectNotes({ $ne: null }, ownerId)).toEqual({ kind: "notFound" });
  });
});
